apiVersion: apps/v1
kind: Deployment
metadata:
  name:  order-microservice-dep
  labels:
    app:  order-microservice
spec:
  selector:
    matchLabels:
      app: order-microservice
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  order-microservice
    spec:
      containers:
      - name:  order-microservice-container
        image:  classpathio/order-microservice:1.0.0
        ports:
        - containerPort:  8222
          name:  app