apiVersion: v1
kind: Pod
metadata:
  labels:
    app: order-microservice
  name: order-microservice
spec:
  containers:
  - image: classpathio/order-microservice
    name: order-microservice
  restartPolicy: Always