apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: order-microservice-rs
  labels:
    app: order-microservice-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: "order-microservice"
  template:
    metadata:
      labels:
        app: "order-microservice"
        env: "dev"
        version: "v1"
        tier: "backend"
    spec:        
     containers:
      - name: "order-microservice"
        image: "classpathio/order-microservice:latest"
        imagePullPolicy: IfNotPresent
        env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "dev"
        volumeMounts:
          - name: "app-config"
            mountPath: "/app/config/"
     volumes:
      - name: "app-config"
        configMap:
          name: "order-microservice-cm"


--- 
kind: ConfigMap
apiVersion: v1
metadata:
  name: order-microservice-cm
data:
  application-dev.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 8222
  application-qa.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 8333
  application-prod.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 6666
--- 
apiVersion: v1
kind: Service
metadata:
  name: order-microservice-svc
spec:
  selector:
    app: order-microservice
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8222
