apiVersion: v1
kind: Pod
metadata:
  name: "order-microservice"
  labels:
    app: "order-microservice"
spec:
  containers:
    - name: "order-microservice"
      image: "classpathio/order-microservice:latest"
      imagePullPolicy: IfNotPresent
      env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "dev"
      volumeMounts:
        - name: "app-config"
          mountPath: "/app/config/"
  volumes:
    - name: "app-config"
      configMap:
        name: "order-microservice-cm"


--- 
kind: ConfigMap
apiVersion: v1
metadata:
  name: order-microservice-cm
data:
  application-dev.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 6666
  application-qa.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 8333
  application-prod.yaml: |-
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: welcome
        driver-class-name: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
    server:
      port: 8444
