server:
  port: 8222
spring:
  datasource:
    url: jdbc:h2:mem:orders_db
    username: sa
    password: welcome
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect    

